#pragma once
#include "vector.hpp"
#include <tuple>

// We have always used Github Copilot when coding, so some lines were generated by it, but we have always checked and understood the code prompted. Although it helped with line-by-line writing, the logic of the implementation comes fully from us.


class Body {
public:
    Body(const double& mass, const Vector& position, const Vector& velocity,
    double size = 8.0, std::tuple<double, double, double> color = {1, 1, 1});

    double mass;
    Vector position;
    Vector velocity;

    double size;
    std::tuple<double,double,double> color;
};
