#pragma once
#include <cmath>

// We have always used Github Copilot when coding, so some lines were generated by it, but we have always checked and understood the code prompted. Although it helped with line-by-line writing, the logic of the implementation comes fully from us.


class Vector {
public:
    explicit Vector(double x = 0, double y = 0);

    double norm2() const;
    double norm() const;
    void normalize();

    double operator[](int i) const;
    double& operator[](int i);

    double data[2];
};

Vector operator+(const Vector& a, const Vector& b);
Vector operator-(const Vector& a, const Vector& b);
Vector operator*(const double a, const Vector& b);
Vector operator*(const Vector& a, const double b);
Vector operator*(const Vector& a, const Vector& b);
Vector operator/(const Vector& a, const double b);
double dot(const Vector& a, const Vector& b);
